server:
  port: ${PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: DocumentManagement
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
      continue-on-error: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: document-management
